---
title: "R Notebook"
output: html_notebook
---

Store the url
```{r}
url <- ("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=2017-01")
```
Copy over json file
```{r}
jsonfile <- fromJSON(url)
```
Getting the dates we want
```{r}
dates <- c("2018-01", "2017-12", "2017-11", "2017-10", "2017-09", "2017-08", "2017-07", "2017-06", "2017-05", "2017-04", "2017-03", "2017-02", "2017-01")


```


Creating a loop - telling the api to go to the url and paste the information above, the date, into the url and give us the category from the json file
```{r}
resultslist = c()
for (i in dates){
  #store the full url in an object
  url <- paste("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=",i, sep="")
  #grab the JSON
  jsonfile <- fromJSON(url)
  print(jsonfile[['category']])
  category <- jsonfile[['category']]
  resultslist = c(resultslist, category)
}
```

```{r}
resultslistdates = c()
for (i in dates){
  #store the full url in an object
  url <- paste("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=",i, sep="")
  #grab the JSON
  jsonfile <- fromJSON(url)
  print(jsonfile[['month']])
  month <- jsonfile[['month']]
  resultslistdates = c(resultslistdates, month)
}
```
repeat process and change the month for location data
```{r}
resultslistlocation = c()
for (i in dates){
  #store the full url in an object
  url <- paste("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=",i, sep="")
  #grab the JSON
  jsonfile <- fromJSON(url)
  print(jsonfile[['location']][['street']][['name']])
  location <- jsonfile[['location']][['street']][['name']]
  resultslistlocation = c(resultslistlocation, location)
}
```
Getting latitude and longitude
```{r}
resultslistlocationlat = c()
for (i in dates){
  #store the full url in an object
  url <- paste("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=",i, sep="")
  #grab the JSON
  jsonfile <- fromJSON(url)
  print(jsonfile[['location']][['latitude']])
  locationlat <- jsonfile[['location']][['latitude']]
  resultslistlocationlat = c(resultslistlocationlat, locationlat)
}
```

```{r}
resultslistlocationlong = c()
for (i in dates){
  #store the full url in an object
  url <- paste("https://data.police.uk/api/crimes-street/all-crime?lat=52.6258&lng=-2.1918&date=",i, sep="")
  #grab the JSON
  jsonfile <- fromJSON(url)
  print(jsonfile[['location']][['longitude']])
  locationlong <- jsonfile[['location']][['longitude']]
  resultslistlocationlong = c(resultslistlocationlong, locationlong)
}
```
create a table
```{r}
crimestats <- data.frame(resultslist, resultslistdates, resultslistlocation, resultslistlocationlat, resultslistlocationlong)
colnames(crimestats)<-c("Crime type","Date","Street","Latitude","Longitude")
```
```{r}
write.csv(crimestats, "Codsallcrime.csv")
```

